server:
  port: 8085
springfox:
  documentation:
    auto-startup: false
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    contentnegotiation:
      favor-parameter: true
    log-request-details: true
  liquibase:
    enabled: true
    contexts: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
    hibernate.ddl-auto: none
  datasource:
    url: jdbc:tc:postgresql:10.9://localhost/test
    username: test
    password: test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    name: main

resilience4j.retry:
  instances:
    backendA:
      maxRetryAttempts: 5
      waitDuration: 3s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - java.lang.RuntimeException

management:
  endpoint:
    health.show-details: always
  endpoints:
    web:
      base-path: /info
      exposure:
        include: '*'
        exclude: ''

jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES

logging:
  level:
    org:
      springframework:
        web: debug
application:
  pass: ENC(HW2w0C4L+3iK0+52xhZesA==)
  name: @project.artifactId@
  version: @project.version@